version: '3'

services:
  infinitefuturednode0:
    container_name: infinitefuturednode0
    image: "tendermint/infinitefuturednode"
    ports:
      - "26656-26657:26656-26657"
    environment:
      - ID=0
      - LOG=${LOG:-infinitefutured.log}
    volumes:
      - ./build:/infinitefutured:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.2

  infinitefuturednode1:
    container_name: infinitefuturednode1
    image: "tendermint/infinitefuturednode"
    ports:
      - "26659-26660:26656-26657"
    environment:
      - ID=1
      - LOG=${LOG:-infinitefutured.log}
    volumes:
      - ./build:/infinitefutured:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.3

  infinitefuturednode2:
    container_name: infinitefuturednode2
    image: "tendermint/infinitefuturednode"
    environment:
      - ID=2
      - LOG=${LOG:-infinitefutured.log}
    ports:
      - "26661-26662:26656-26657"
    volumes:
      - ./build:/infinitefutured:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.4

  infinitefuturednode3:
    container_name: infinitefuturednode3
    image: "tendermint/infinitefuturednode"
    environment:
      - ID=3
      - LOG=${LOG:-infinitefutured.log}
    ports:
      - "26663-26664:26656-26657"
    volumes:
      - ./build:/infinitefutured:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.5

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 192.168.10.0/16

