---

- name: Copy binary
  copy:
    src: "{{GAIACLI_BINARY}}"
    dest: /usr/bin/infinitefuturecli
    mode: 0755
  notify: restart infinitefuturecli

- name: Copy service
  template:
    src: infinitefuturecli.service.j2
    dest: /etc/systemd/system/infinitefuturecli.service
  notify: systemctl

