---

- name: Fetch genesis.json
  fetch: "src=/home/infinitefutured/.infinitefutured/config/genesis.json dest={{GENESISFILE}} flat=yes"
  run_once: yes
  become: yes
  become_user: infinitefutured

- name: Fetch config.toml
  fetch: "src=/home/infinitefutured/.infinitefutured/config/config.toml dest={{CONFIGFILE}} flat=yes"
  run_once: yes
  become: yes
  become_user: infinitefutured

